do shell lint in batch rather than exit on first failure

diff --git a/.github/workflows/shell-lint.yaml b/.github/workflows/shell-lint.yaml
--- a/.github/workflows/shell-lint.yaml
+++ b/.github/workflows/shell-lint.yaml
@@ -30,12 +30,30 @@ jobs:
       - name: Install dependencies
         run: |
           pip install --upgrade pip
-          pip install shellcheck-py shfmt-py
+          pip install shfmt-py shellcheck-py
 
       - name: Run shell format
         run: |
-          find src -type f -name '*.sh' -print0 | xargs -0 -r shfmt -d -i 4 --
+          globalStatus=0
+
+          while IFS= read -r -d '' f; do
+            if ! shfmt -d -i 4 -- "$f"; then
+              echo "[ERROR] shfmt failed for $f"
+              globalStatus=1
+            fi
+          done < <(find src -type f -name '*.sh' -print0)
+
+          exit $globalStatus
 
       - name: Run shell check
         run: |
-          find src -type f -name '*.sh' -print0 | xargs -0 -r shellcheck -x -e SC2034 --
+          globalStatus=0
+
+          while IFS= read -r -d '' f; do
+            if ! shellcheck -x -e SC2034 -- "$f"; then
+              echo "[ERROR] shellcheck failed for $f"
+              globalStatus=1
+            fi
+          done < <(find src -type f -name '*.sh' -print0)
+
+          exit $globalStatus
